[package]
name = "restorer"
version = "0.1.0"
edition = "2024"

[dependencies]
goblin = "0.10.1"
log = "0.4.27"
thiserror = "2.0.16"
colored = "3.0.0"
pe-utils = { path = "../pe-utils" }

[lib]
name = "restorer"
path = "src/lib.rs"